#!/bin/bash


#-----------------------------------------------------------------------------
# Play Framework HTTP-Server Configuration variables
#-----------------------------------------------------------------------------

# Uncomment to override default HTTP server port '9000' and address '0.0.0.0'
#export PLAY_HTTP_PORT=
#export PLAY_HTTP_ADDRESS=


# APPLICATION_SECRET MUST be a random String of at least 32 characters
export APPLICATION_SECRET=TODO

# Location of the PID-File
export PID_FILE="/tmp/bwhc-backend.pid"

#-----------------------------------------------------------------------------


#-----------------------------------------------------------------------------
# bwHC Configuration Variables
#-----------------------------------------------------------------------------

# Optional TODO: Adapt BWHC_BASE_DIR
if [ -z ${BWHC_BASE_DIR+x} ]; then
  # only export, if not already set
  export BWHC_BASE_DIR=$(pwd)
fi


#TODO: adapt ZPM site name
export ZPM_SITE=TODO


# Optional: Adapt path to bwHCConnector config file
export BWHC_CONNECTOR_CONFIG=$BWHC_BASE_DIR/bwhcConnectorConfig.xml


#TODO adapt data directories
export BWHC_DATA_ENTRY_DIR=TODO

export BWHC_QUERY_DATA_DIR=TODO

export BWHC_USER_DB_DIR=TODO

export BWHC_HGNC_DIR="$BWHC_BASE_DIR/hgnc_data/"

#-----------------------------------------------------------------------------
